// Runs after `next build` (npm run build): locks the static site down with a Content-Security-Policy and writes
// out/_headers with the security headers.
//
// - Every page gets the policy as a <meta> tag. That works on any host, GitHub Pages included, and covers scripts,
//   styles, images and connections. Browsers ignore frame-ancestors in a <meta> tag: the frame guard in
//   app/layout.tsx covers framing there.
// - out/_headers sends the same policy, plus frame-ancestors, HSTS, X-Frame-Options, X-Content-Type-Options,
//   Referrer-Policy and Permissions-Policy as real response headers, on a host that reads the file (Cloudflare
//   Pages; README → Security headers). GitHub Pages can't send headers and ignores it.
//
// Scripts: no 'unsafe-inline'. Next.js puts a few small scripts inline in each page (the page's data); each one is
// allowed by its SHA-256 hash, worked out here from the built pages.
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import nextEnv from "@next/env";

const OUT = "out";
// The 2,000-character limit Cloudflare Pages puts on one header in _headers.
const HEADER_MAX = 2000;

nextEnv.loadEnvConfig(process.cwd()); // the same .env files `next build` read
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabase = supabaseUrl ? new URL(supabaseUrl).origin : "";
if (!supabase) console.warn("security-headers: NEXT_PUBLIC_SUPABASE_URL isn't set, so the site may not connect to Supabase.");

const pages = fs
  .readdirSync(OUT, { recursive: true })
  .filter((f) => f.endsWith(".html"))
  .map((f) => path.join(OUT, f));
if (pages.length === 0) throw new Error(`security-headers: no pages in ./${OUT}. Run it after next build.`);

// Inline scripts are the <script> tags without a src.
const INLINE_SCRIPT = /<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/gi;
const hashes = new Set();
for (const file of pages) {
  for (const [, body] of fs.readFileSync(file, "utf8").matchAll(INLINE_SCRIPT)) {
    if (body) hashes.add(`'sha256-${createHash("sha256").update(body, "utf8").digest("base64")}'`);
  }
}

const policy = [
  "default-src 'self'",
  `script-src 'self' ${[...hashes].sort().join(" ")}`.trim(),
  // React sets some styles inline (style="…"); styles can't run code.
  "style-src 'self' 'unsafe-inline'",
  // Profile photos and event covers: Supabase Storage, or a link to an image anywhere on https.
  `img-src 'self' data: https: ${supabase}`.trim(),
  "font-src 'self'",
  // The site only talks to itself and its Supabase project.
  `connect-src 'self' ${supabase}`.trim(),
  "manifest-src 'self'",
  "worker-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
];
const metaPolicy = policy.join("; ");
const headerPolicy = [...policy, "frame-ancestors 'none'"].join("; ");
if (headerPolicy.length > HEADER_MAX) {
  throw new Error(
    `security-headers: the Content-Security-Policy is ${headerPolicy.length} characters, over Cloudflare Pages' ` +
      `${HEADER_MAX}-character limit for a header (${hashes.size} inline scripts). Give each page its own policy in _headers.`,
  );
}

// The <meta> goes right after <meta charset> (which has to stay in the first 1024 bytes), before any script.
const META = `<meta http-equiv="Content-Security-Policy" content="${metaPolicy.replaceAll('"', "&quot;")}"/>`;
const OLD_META = /<meta http-equiv="Content-Security-Policy"[^>]*>/gi;
const CHARSET = /<meta charset="?utf-8"?\s*\/?>/i;
for (const file of pages) {
  const html = fs.readFileSync(file, "utf8").replace(OLD_META, "");
  const anchor = html.match(CHARSET) ?? html.match(/<head[^>]*>/i);
  if (!anchor) throw new Error(`security-headers: ${file} has no <head>.`);
  const at = anchor.index + anchor[0].length;
  fs.writeFileSync(file, html.slice(0, at) + META + html.slice(at));
}

fs.writeFileSync(
  path.join(OUT, "_headers"),
  `# Security headers for every response. Generated by scripts/security-headers.mjs on each build; read by Cloudflare
# Pages (README → Security headers). GitHub Pages ignores this file.
/*
  Content-Security-Policy: ${headerPolicy}
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()
  ! Access-Control-Allow-Origin
`,
);

console.log(
  `security-headers: Content-Security-Policy added to ${pages.length} pages (${hashes.size} inline scripts allowed by hash); ${OUT}/_headers written.`,
);
